//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace work_01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        public int TraineeId { get; set; }
        public string TraineeName { get; set; }
        public System.DateTime JoinDate { get; set; }
        public int CourseId { get; set; }
        public string PicturePath { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
